name       : papirus-icon-theme
version    : '1155' # From git rev-list count
release    : 9
source     :
    - git|https://github.com/PapirusDevelopmentTeam/papirus-icon-theme.git : 08a25af5890d1e6cda73a51e9c33cfdffcdf5e2a
license    : LGPL-3.0
component  : desktop.theme
summary    : A free and open source SVG icon theme for Linux systems
description: |
    A free and open source SVG icon theme for Linux systems
install    : |
    %make_install
    for i in 16 22 24 32 48 64; do
        # Temporarily add some symlinks for Solus SC Third Party items
        icoDir=/usr/share/icons/Papirus/${i}x${i}
        appsLoc=${icoDir}/apps/
        ln -s ${appsLoc}google-earth.svg $installdir/${appsLoc}/earth.svg
        ln -s ${appsLoc}gitkraken.svg $installdir/${appsLoc}/web-github.svg
        ln -s ${appsLoc}slack.svg $installdir/${appsLoc}/web-slack.svg
        # Temporarily add some symlinks for various Solus SC components
        ln -s ${appsLoc}/gnome-logo-icon.svg $installdir/${appsLoc}/desktop-environment-gnome.svg
    done
