name       : papirus-icon-theme
version    : '20190802'
release    : 49
source     :
    - https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/20190802.tar.gz : d2a3a31215704e7e7bdde47c0c6d3040b5b585c058cecd35fdb2ffaa642eefcd
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - ^solus-sc-icons : desktop.theme
summary    :
    - A free and open source SVG icon theme for Linux systems
    - ^solus-sc-icons : Icons required for the Solus Software Center
description: |
    A free and open source SVG icon theme for Linux systems
patterns   :
    - /usr/share/icons/Papirus
    - ^solus-sc-icons : /usr/share/icons/solus-sc
rundeps    :
    - hicolor-icon-theme
replaces   :
    - papirus-adapta-icon-theme
setup      : |
    rm -r ePapirus
install    : |-
    %make_install
    scDir=$installdir/usr/share/icons/solus-sc
    thirdPartyIcons=(
        "android-file-transfer"
        "android-studio"
        "bitwig-studio"
        "enpass"
        "flash"
        "google-chrome"
        "google-chrome-beta"
        "google-chrome-unstable"
        "google-earth"
        "gitkraken"
        "idea"
        "insync"
        "mendeleydesktop"
        "moneydance"
        "ocenaudio"
        "plex"
        "pycharm"
        "rider"
        "rubymine"
        "skype"
        "slack"
        "spotify"
        "sublime-text"
        "viber"
        "webstorm"
        "wps-office-wpsmain"
    )

    for i in 16 22 24 32 48 64; do
        # Temporarily add some symlinks for Solus SC Third Party items
        icoDir=/usr/share/icons/Papirus/${i}x${i}
        appsLoc=${icoDir}/apps/
        mimetypesLoc=${icoDir}/mimetypes/
        placesLoc=${icoDir}/places/
        ln -s ${appsLoc}google-earth.svg $installdir/${appsLoc}/earth.svg
        ln -s ${appsLoc}gitkraken.svg $installdir/${appsLoc}/web-github.svg
        ln -s ${appsLoc}slack.svg $installdir/${appsLoc}/web-slack.svg
        # Add some SC category items
        ln -s ${appsLoc}gnome-video-arcade.svg $installdir/${appsLoc}/ds-emulator.svg
        ln -s ${mimetypesLoc}application-x-java.svg $installdir/${mimetypesLoc}/applications-java.svg
        ln -s ${placesLoc}kde-logo.svg $installdir/${placesLoc}/desktop-environment-kde.svg
    done
    # Solus Software Center icon installation. It's an abomination, I know. I'm sorry.
    for i in 16 22 24 32 48 64; do # First install majority of icons
        for icon in "${thirdPartyIcons[@]}"; do
            install -Dm00644 $installdir/$appsLoc/${icon}.svg $scDir/${i}x${i}/apps/${icon}.svg
        done
    done
    for i in 16 22 24; do # im-google-talk is special. It's in actions and only a small range of sizes
        actionsDir=/usr/share/icons/Papirus/${i}x${i}/actions
        install -Dm00644 $installdir/$actionsDir/im-google-talk.svg $scDir/${i}x${i}/actions/im-google-talk.svg
    done
    install -Dm00644 $pkgfiles/index.theme $scDir/index.theme
    install -Dm00644 $pkgfiles/Papirus-Adapta@index.theme $installdir/usr/share/icons/Papirus-Adapta/index.theme
    install -Dm00644 $pkgfiles/Papirus-Adapta-Nokto@index.theme $installdir/usr/share/icons/Papirus-Adapta-Nokto/index.theme
