name       : papirus-icon-theme
version    : '20170324'
release    : 4
source     :
    - https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/20170324.tar.gz : 8f2d6abbdb5f2e7d31cd47c9583f529e350a04c6d2d8c66541ee9b2618cbfbb2
license    : LGPL-3.0
component  : desktop.theme
summary    : A free and open source SVG icon theme for Linux systems
description: |
    A free and open source SVG icon theme for Linux systems
install    : |
    %make_install
