name       : papirus-icon-theme
version    : '20170616'
release    : 8
source     :
    - https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/20170616.tar.gz : 646f5e4bbc4bced59f7e56d3b5b40b0a2e82d58d7a4999218807b94e4f8f06f2
license    : LGPL-3.0
component  : desktop.theme
summary    : A free and open source SVG icon theme for Linux systems
description: |
    A free and open source SVG icon theme for Linux systems
install    : |
    %make_install
    for i in 16 22 24 32 48 64; do
        # Temporarily add some symlinks for Solus SC Third Party items
        icoDir=/usr/share/icons/Papirus/${i}x${i}
        appsLoc=${icoDir}/apps/
        ln -s ${appsLoc}google-earth.svg $installdir/${appsLoc}/earth.svg
        ln -s ${appsLoc}gitkraken.svg $installdir/${appsLoc}/web-github.svg
        ln -s ${appsLoc}slack.svg $installdir/${appsLoc}/web-slack.svg
        # Temporarily add some symlinks for various Solus SC components
        ln -s ${appsLoc}/gnome-logo-icon.svg $installdir/${appsLoc}/desktop-environment-gnome.svg
        ln -s ${icoDir}/mimetypes/text-x-haskell.svg $installdir/${appsLoc}/applications-haskell.svg
    done
