name       : papirus-icon-theme
version    : '20170219'
release    : 2
source     :
    - https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/20170219.tar.gz : 2431adf87131f50a9255fa3684f75e910719926ed1c72620bc85ffb876a6e06e
license    : LGPL-3.0
component  : desktop.theme
summary    : A free and open source SVG icon theme for Linux systems
description: |
    A free and open source SVG icon theme for Linux systems
install    : |
    %make_install
