name       : papirus-icon-theme
version    : '20170616'
release    : 6
source     :
    - https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/20170616.tar.gz : 646f5e4bbc4bced59f7e56d3b5b40b0a2e82d58d7a4999218807b94e4f8f06f2
license    : LGPL-3.0
component  : desktop.theme
summary    : A free and open source SVG icon theme for Linux systems
description: |
    A free and open source SVG icon theme for Linux systems
install    : |
    %make_install
