name       : papirus-icon-theme
version    : '20230601'
release    : 81
source     :
    - https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/refs/tags/20230601.tar.gz : 92d2e487cd3572e90c8cd28ada407cf0d28a81a4f4cb16cb537d1b92f7269486
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - ^solus-sc-icons : desktop.theme
summary    :
    - A free and open source SVG icon theme for Linux systems
    - ^solus-sc-icons : Icons required for the Solus Software Center
description: |
    A free and open source SVG icon theme for Linux systems
patterns   :
    - /usr/share/icons/Papirus
    - ^solus-sc-icons : /usr/share/icons/solus-sc
rundeps    :
    - hicolor-icon-theme
replaces   :
    - papirus-adapta-icon-theme
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-redesign-System-Software-Install.patch
    rm -r ePapirus*
install    : |
    %make_install
    scDir=$installdir/usr/share/icons/solus-sc
    thirdPartyIcons=(
        "android-studio"
        "bitwig-studio"
        "enpass"
        "google-chrome"
        "google-chrome-beta"
        "google-chrome-unstable"
        "google-earth"
        "gitkraken"
        "idea"
        "insync"
        "mendeleydesktop"
        "moneydance"
        "ocenaudio"
        "plex"
        "pycharm"
        "rider"
        "rubymine"
        "skype"
        "slack"
        "spotify"
        "sublime-text"
        "teamviewer"
        "viber"
        "webstorm"
    )

    for i in 16 22 24 32 48 64; do
        # Temporarily add some symlinks for Solus SC Third Party items
        icoDir=/usr/share/icons/Papirus/${i}x${i}
        appsLoc=${icoDir}/apps/
        mimetypesLoc=${icoDir}/mimetypes/
        placesLoc=${icoDir}/places/
        ln -sv ${appsLoc}google-earth.svg $installdir/${appsLoc}/earth.svg
        ln -sv ${appsLoc}gitkraken.svg $installdir/${appsLoc}/web-github.svg
        ln -sv ${appsLoc}slack.svg $installdir/${appsLoc}/web-slack.svg
        # Add some SC category items
        ln -sv ${appsLoc}gnome-video-arcade.svg $installdir/${appsLoc}/ds-emulator.svg
        ln -sv ${appsLoc}kde-logo.svg $installdir/${placesLoc}/desktop-environment-kde.svg
        ln -sv ${mimetypesLoc}text-x-java.svg $installdir/${mimetypesLoc}/applications-java.svg
        # Solus Software Center icon installation. It's an abomination, I know. I'm sorry.
        for icon in "${thirdPartyIcons[@]}"; do
            install -Dm00644 $installdir/$appsLoc/${icon}.svg $scDir/${i}x${i}/apps/${icon}.svg
        done
    done
    for i in 16 22 24; do # im-google-talk is special. It's in actions and only a small range of sizes
        actionsDir=/usr/share/icons/Papirus/${i}x${i}/actions
        install -Dm00644 $installdir/$actionsDir/im-google-talk.svg $scDir/${i}x${i}/actions/im-google-talk.svg
    done
    install -Dm00644 $pkgfiles/index.theme $scDir/index.theme
    install -Dm00644 $pkgfiles/Papirus-Adapta@index.theme $installdir/usr/share/icons/Papirus-Adapta/index.theme
    install -Dm00644 $pkgfiles/Papirus-Adapta-Nokto@index.theme $installdir/usr/share/icons/Papirus-Adapta-Nokto/index.theme
    rm -f $installdir/usr/share/icons/Papirus/**/apps/{dcc_nav*,dde*,*deepin*,io.elementary*,uos*,com.github.cassidyjames*}
