name       : papirus-icon-theme
version    : 20170715.15
release    : 13
source     :
    - git|https://github.com/PapirusDevelopmentTeam/papirus-icon-theme.git : 52af71df26a9375aa65c435c521cc002008f938f
license    : LGPL-3.0
component  : desktop.theme
summary    : A free and open source SVG icon theme for Linux systems
description: |
    A free and open source SVG icon theme for Linux systems
install    : |
    %make_install
    for i in 16 22 24 32 48 64; do
        # Temporarily add some symlinks for Solus SC Third Party items
        icoDir=/usr/share/icons/Papirus/${i}x${i}
        appsLoc=${icoDir}/apps/
        ln -s ${appsLoc}google-earth.svg $installdir/${appsLoc}/earth.svg
        ln -s ${appsLoc}gitkraken.svg $installdir/${appsLoc}/web-github.svg
        ln -s ${appsLoc}slack.svg $installdir/${appsLoc}/web-slack.svg
        # Temporarily add some symlinks for various Solus SC components
        ln -s ${appsLoc}/gnome-logo-icon.svg $installdir/${appsLoc}/desktop-environment-gnome.svg
    done
    # elementaryOS specific, not needed in Solus
    rm -rf $installdir/usr/share/icons/ePapirus
