name       : papirus-icon-theme
version    : '20170510'
release    : 5
source     :
    - https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/20170510.tar.gz : 5b31f29f96dc2081ccd09311bb10866ea0c43db85d3286d8ed983b9ad4d826a6
license    : LGPL-3.0
component  : desktop.theme
summary    : A free and open source SVG icon theme for Linux systems
description: |
    A free and open source SVG icon theme for Linux systems
install    : |
    %make_install
