name       : papirus-icon-theme
version    : 20170118
release    : 1
source     :
    - https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/20170118.tar.gz : 0eb83a24b518ed926e9abf98a66d33715fc2123f575666890e42c58ddaf8ef4b
license    : LGPL-3.0
component  : desktop.theme
summary    : A free and open source SVG icon theme for Linux systems
description: |
    A free and open source SVG icon theme for Linux systems
install    : |
    %make_install
