name       : papirus-icon-theme
version    : '20170309'
release    : 3
source     :
    - https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/20170309.tar.gz : 46c38b1c71b2b0732e3341c81ff990f0c4385fb9685994f770e70c262bb2cc28
license    : LGPL-3.0
component  : desktop.theme
summary    : A free and open source SVG icon theme for Linux systems
description: |
    A free and open source SVG icon theme for Linux systems
install    : |
    %make_install
